# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 350, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 100, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("c"))
        self.cButton.setGeometry(QtCore.QRect(100, 100, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 100, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(280, 100, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 170, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(280, 170, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 170, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 170, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 240, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(280, 240, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 240, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 240, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 310, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(280, 310, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 310, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 310, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.plus_minus())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.equals())
        self.equalButton.setGeometry(QtCore.QRect(280, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(190, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#Remove a character
    def remove_it(self):
        #Grab what's on the screen already
        screen=self.outputLabel.text()
        #Remove last item in list/string
        screen=screen[:-1]
        #Output back to the screen
        self.outputLabel.setText(screen)

    def plus_minus(self):
        screen=self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-",""))
        else:
            self.outputLabel.setText(f'-{screen}')   

    def equals(self):
        screen=self.outputLabel.text()
        try:
            answer=eval(screen)
            #Output answer to the screen
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText("Error")    
#Add a decimal
    def dot_it(self):
        screen=self.outputLabel.text()
        if "." in screen:
            pass    
        else:
            self.outputLabel.setText(f'{screen}.')
    def press_it(self,pressed):
        if pressed == "c":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text()=="0":
                self.outputLabel.setText("")    
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.multiplyButton.setText(_translate("MainWindow", "x"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
